name: WoWDatabaseEditor

on:
  push:
  pull_request:

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    strategy:
      matrix:
        os: [win8-x64]
        configuration: [Release]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Pull submodules
      run: git submodule update --init --recursive

    - name: Publish LoaderAvalonia
      run: |
       dotnet publish -c Release --self-contained false -f net6.0 -o bin/wowdatabaseeditor-avalonia-win/ LoaderAvalonia/LoaderAvalonia.csproj -r win8-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false -p:DebugType=none

    - name: Publish Updater
      run: |
       dotnet publish -c Release --self-contained false -f net6.0 -o bin/wowdatabaseeditor-avalonia-win/ Updater/Updater.csproj -r win8-x64 -p:PublishSingleFile=true -p:PublishTrimmed=false -p:DebugType=none
       mv bin\wowdatabaseeditor-avalonia-win\Updater.exe _Updater.exe

    - name: Publish WPP Loader
      run: |
       dotnet publish -c Release --self-contained false -f net6.0 -o bin/wowdatabaseeditor-avalonia-win/parser WoWPacketParserLoader -r win8-x64

    - name: Publish Modules
      run: |
       cd ../
       mkdir modules
       dotnet publish WDE.Github/WDE.Github.csproj -o modules/ -c Release -f net6.0
       cp modules/WDE.Github.dll ../bin/wowdatabaseeditor-avalonia-win/WDE.Github.dll

    - name: Move WowPacketParser
      run: |
       FOR %%A IN (bin\wowdatabaseeditor-avalonia-win\parser,bin\wowdatabaseeditor-avalonia-mac\parser,bin\wowdatabaseeditor-avalonia-linux\parser) DO ( mkdir %%A\Parsers & cd %%A & ( FOR %%X in (WowPacketParserModule.*) DO ( move %%X Parsers\%%X ) ) & cd ..\..\..\ )
      
    - name: Download third party libs
      run: |
       curl -fsSL -o bin/wowdatabaseeditor-avalonia-win/storm.dll https://github.com/BAndysc/StormCascLibBinary/releases/download/windows/StormLib.dll
       curl -fsSL -o bin/wowdatabaseeditor-avalonia-win/casc.dll https://github.com/BAndysc/StormCascLibBinary/releases/download/windows/CascLib.dll
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: WPP-${{ matrix.os }}-${{ matrix.configuration }}
        path: bin/wowdatabaseeditor-avalonia-win/
